# Generated by Django 4.2 on 2023-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
